"""add columns descripcion and foto_de_perfil in usuario

Revision ID: 07eb2fae5891
Revises: 32c449b3aa35
Create Date: 2024-11-02 23:46:44.016607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '07eb2fae5891'
down_revision: Union[str, None] = '32c449b3aa35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('usuario', sa.Column('foto_de_perfil', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'foto_de_perfil')
    op.drop_column('usuario', 'descripcion')
    # ### end Alembic commands ###
