"""create table Puntuacion

Revision ID: 2340bbcf6dae
Revises: 07eb2fae5891
Create Date: 2024-11-08 00:14:49.680447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2340bbcf6dae'
down_revision: Union[str, None] = '07eb2fae5891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puntuacion',
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_libro'], ['libro.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_libro')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puntuacion')
    # ### end Alembic commands ###
