"""create table comunidad

Revision ID: 3136aee4fdc8
Revises: 2340bbcf6dae
Create Date: 2024-11-09 16:00:52.322154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3136aee4fdc8'
down_revision: Union[str, None] = '2340bbcf6dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunidad',
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('imagen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo', sa.Enum('PUBLICO', 'PRIVADO', name='tipocomunidad'), nullable=False),
    sa.Column('id_creador', sa.Integer(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_creador'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comunidad_nombre'), 'comunidad', ['nombre'], unique=False)
    op.create_table('usuariocomunidad',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_comunidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_comunidad'], ['comunidad.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_comunidad')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuariocomunidad')
    op.drop_index(op.f('ix_comunidad_nombre'), table_name='comunidad')
    op.drop_table('comunidad')
    sa.Enum(name="tipocomunidad").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
