"""create table reseñas

Revision ID: 32c449b3aa35
Revises: d85737f24bee
Create Date: 2024-10-27 19:36:32.099098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32c449b3aa35'
down_revision: Union[str, None] = 'd85737f24bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reseña',
    sa.Column('contenido', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_libro'], ['libro.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_libro'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reseña')
    # ### end Alembic commands ###
