"""create table libros

Revision ID: 54a37739ebf9
Revises: ea338489d696
Create Date: 2024-10-21 15:29:14.016990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54a37739ebf9'
down_revision: Union[str, None] = 'ea338489d696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genero',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_genero_id'), 'genero', ['id'], unique=False)

    op.create_table('libro',
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_publicacion', sa.Date(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portada', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_autor', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_autor'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libro_isbn'), 'libro', ['isbn'], unique=True)
    op.create_index(op.f('ix_libro_nombre'), 'libro', ['nombre'], unique=False)
    op.create_table('librogenero',
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('id_genero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_genero'], ['genero.id'], ),
    sa.ForeignKeyConstraint(['id_libro'], ['libro.id'], ),
    sa.PrimaryKeyConstraint('id_libro', 'id_genero')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('librogenero')
    op.drop_index(op.f('ix_libro_nombre'), table_name='libro')
    op.drop_index(op.f('ix_libro_isbn'), table_name='libro')
    op.drop_table('libro')
    op.drop_index(op.f('ix_genero_id'), table_name='genero')
    op.drop_table('genero')
    # ### end Alembic commands ###
