"""add imagenes in publicacion

Revision ID: 74fc72929261
Revises: 84c42196773c
Create Date: 2024-11-23 14:04:01.803993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '74fc72929261'
down_revision: Union[str, None] = '84c42196773c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagenpublicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagenpublicacion_id'), 'imagenpublicacion', ['id'], unique=False)
    op.create_table('imagenpublicacionlink',
    sa.Column('id_imagenes', sa.Integer(), nullable=False),
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_imagenes'], ['imagenpublicacion.id'], ),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicacion.id'], ),
    sa.PrimaryKeyConstraint('id_imagenes', 'id_publicacion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagenpublicacionlink')
    op.drop_index(op.f('ix_imagenpublicacion_id'), table_name='imagenpublicacion')
    op.drop_table('imagenpublicacion')
    # ### end Alembic commands ###
