"""add column fecha in Publicacion

Revision ID: 84c42196773c
Revises: 7b80e8becfe6
Create Date: 2024-11-23 13:09:02.891957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c42196773c'
down_revision: Union[str, None] = '7b80e8becfe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publicacion', sa.Column('fecha', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publicacion', 'fecha')
    # ### end Alembic commands ###
