"""create table estanteria

Revision ID: d85737f24bee
Revises: 54a37739ebf9
Create Date: 2024-10-26 11:18:31.308916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd85737f24bee'
down_revision: Union[str, None] = '54a37739ebf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estanteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estanteria_nombre'), 'estanteria', ['nombre'], unique=False)
    op.create_table('libroestanteria',
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('id_estanteria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_estanteria'], ['estanteria.id'], ),
    sa.ForeignKeyConstraint(['id_libro'], ['libro.id'], ),
    sa.PrimaryKeyConstraint('id_libro', 'id_estanteria')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libroestanteria')
    op.drop_index(op.f('ix_estanteria_nombre'), table_name='estanteria')
    op.drop_table('estanteria')
    # ### end Alembic commands ###
