"""add imagenes_ilustrativas to Libro

Revision ID: e22be80f8633
Revises: 3136aee4fdc8
Create Date: 2024-11-10 00:00:58.812817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e22be80f8633'
down_revision: Union[str, None] = '3136aee4fdc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagenilustrativa',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagenilustrativa_id'), 'imagenilustrativa', ['id'], unique=False)
    op.create_table('libroimagenilustrativa',
    sa.Column('id_imagenes_ilustrativas', sa.Integer(), nullable=False),
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_imagenes_ilustrativas'], ['imagenilustrativa.id'], ),
    sa.ForeignKeyConstraint(['id_libro'], ['libro.id'], ),
    sa.PrimaryKeyConstraint('id_imagenes_ilustrativas', 'id_libro')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libroimagenilustrativa')
    op.drop_index(op.f('ix_imagenilustrativa_id'), table_name='imagenilustrativa')
    op.drop_table('imagenilustrativa')
    # ### end Alembic commands ###
